language: go
go:
  - 1.x
notificaitons:
  email:
    recipients: jarrod@vertigrated.com
    on_failure: always
install:
  - go get -u github.com/jarrodhroberson/bais
  - go get -t -v ./...
script:
  - courtney -e
after_success:
  - bash <(curl -s https://codecov.io/bash)