language: go
go:
  - 1.15.x
go_import_path: github.com/jarrodhroberson/bais/bais
notificaitons:
  email:
    recipients: jarrod@vertigrated.com
    on_failure: always
install:
  - go get -t -v ./...
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
