language: go
go:
  - 1.14.x
  - 1.15.x
  - tip
notificaitons:
  email:
    recipients: jarrod@vertigrated.com
    on_failure: always
install:
  - go get -u github.com/jarrodhroberson/bais
  - go get -t -v ./...
script:
  - ./go.test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)